CREATE TABLE categoria(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(100) NOT NULL,
cor VARCHAR(20),
descricao VARCHAR(100),
text VARCHAR(100),
url VARCHAR(100)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;